stages:
  - build
  - deploy

job:
  stage: build
  script:
    - docker build -t rest-core-image .
    
up:
  stage: deploy
  script:
    - "curl -X POST -F token=$TRIGGER_TOKEN -F ref=master https://gitlab.com/api/v4/projects/24046423/trigger/pipeline"
  needs: ["job"]
  