version: '3.3'
services:
  backend:
    container_name: backend
    image: rest-core-image
    ports:
      - 8080:8080
    restart: "always"
    networks:
      app_net:
        ipv4_address: 172.16.238.11

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
